### ISSUE TITLE
Fix seaf-gc error "MySQL server has gone away"

### ISSUE THREAD

**Issue by vmakarenko** [MPDL/KEEPER#320] opened 2019-02-12 10:27 UTC
see keeper_gc.2019-02-09.log@app03-keeper
```
[02/09/19 08:15:11] ../../common/seaf-db.c(895): Error prepare statement SELECT 1 FROM GCID WHERE repo_id = ?: mysql_stmt_prepare failed: MySQL server has gone away.
[02/09/19 08:15:11] ../../common/seaf-db.c(922): Error exec prep stmt: mysql_stmt_execute failed: Duplicate entry '118da70c-36f6-4be0-af30-5cdedf4d025b' for key 'repo_id'.
[02/09/19 08:15:11] gc-core.c(311): Failed to update GCID for repo 118da70c-36f6-4be0-af30-5cdedf4d025b.
```

**Comment by iosifpeterfi** [comment] 2019-02-15 10:46
The mysql server log is full of disconnect messages similar to these:
2019-02-15 10:29:38 140345121249024 [Warning] Aborted connection 14470 to db: 'seahub-db' user: 'seafile' host: 'proxy01-qa-keeper.mpdl.mpg.de' (Got an error reading communication packets)
2019-02-15 10:29:38 140345121048320 [Warning] Aborted connection 14471 to db: 'seahub-db' user: 'seafile' host: 'proxy01-qa-keeper.mpdl.mpg.de' (Got an error reading communication packets)
2019-02-15 10:30:38 140345122453248 [Warning] Aborted connection 14596 to db: 'seahub-db' user: 'seafile' host: 'proxy01-qa-keeper.mpdl.mpg.de' (Got an error reading communication packets)
2019-02-15 10:30:38 140345121048320 [Warning] Aborted connection 14597 to db: 'seahub-db' user: 'seafile' host: 'proxy01-qa-keeper.mpdl.mpg.de' (Got an error reading communication packets)
2019-02-15 10:30:38 140345122051840 [Warning] Aborted connection 14605 to db: 'seahub-db' user: 'seafile' host: 'proxy01-qa-keeper.mpdl.mpg.de' (Got an error reading communication packets)
2019-02-15 10:31:38 140345122453248 [Warning] Aborted connection 14722 to db: 'seahub-db' user: 'seafile' host: 'proxy01-qa-keeper.mpdl.mpg.de' (Got an error reading communication packets)
2019-02-15 10:31:38 140345121449728 [Warning] Aborted connection 14723 to db: 'seahub-db' user: 'seafile' host: 'proxy01-qa-keeper.mpdl.mpg.de' (Got an error reading communication packets)
2019-02-15 10:32:38 140345121449728 [Warning] Aborted connection 14848 to db: 'seahub-db' user: 'seafile' host: 'proxy01-qa-keeper.mpdl.mpg.de' (Got an error reading communication packets)
2019-02-15 10:32:38 140345121650432 [Warning] Aborted connection 14849 to db: 'seahub-db' user: 'seafile' host: 'proxy01-qa-keeper.mpdl.mpg.de' (Got an error reading communication packets)
2019-02-15 10:33:35 140345121048320 [Warning] Aborted connection 14965 to db: 'seafile-db' user: 'seafile' host: 'proxy01-qa-keeper.mpdl.mpg.de' (Got an error reading communication packets)
2019-02-15 10:33:38 140345121851136 [Warning] Aborted connection 14974 to db: 'seahub-db' user: 'seafile' host: 'proxy01-qa-keeper.mpdl.mpg.de' (Got an error reading communication packets)

I have reviewed sections of the code and working on a commit to fix these errors.

**Comment by vmakarenko** [comment] 2019-02-18 14:00
FYI:
seaf-gc source code:
https://github.com/haiwen/seafile-server/blob/master/scripts/seaf-gc.sh 
https://github.com/haiwen/seafile-server/blob/master/server/gc/seafserv-gc.c
https://github.com/haiwen/seafile-server/blob/master/server/gc/gc-core.c
https://github.com/haiwen/seafile-server/blob/master/server/gc/gc-core.h

**Comment by iosifpeterfi** [comment] 2019-02-18 16:36
I saw the code, however this has nothing related to the GCID table. This tells me that the pro version of the source is different. We need to forward this to seafile support.

**Comment by iosifpeterfi** [comment] 2019-02-18 16:41
There are 4 timeout settings controlling this:
in haproxy.cfg:
timeout server
timeout client
in my.cfg: 
net_read_timeout
net_write_timeout

If we increase this timeout it will keep the connection open while the indexing happens.

The issue is in the code, when manages this database connection. It should either disconnect from the database and reconnect when the indexing is over, or regularly ping the database to maintain the connectivity.

**Comment by iosifpeterfi** [comment] 2019-02-18 16:43
Increasing the value of this variables too high would lead to lingering inactive database connections, taking up unneeded resources from the database server.

**Comment by iosifpeterfi** [comment] 2019-02-25 09:38
Discussed the details with Seafile support. They said will fix it in the next release.

**Comment by iosifpeterfi** [comment] 2019-06-27 15:09
This has been fixed by seafile in version 7.x.x of the garbage collector.

**Closed** 2020-06-04 08:25 UTC
