### ISSUE TITLE
Orange issues and other css bugs

### ISSUE THREAD

**Issue by kleinfe** [MPDL/KEEPER#186] opened 2017-07-13 06:58 UTC
![1 3_1](https://user-images.githubusercontent.com/1484773/28154176-6111b812-67a9-11e7-9a29-001bba030fcf.png)
![1 3_2](https://user-images.githubusercontent.com/1484773/28154178-612bdbf2-67a9-11e7-8fa8-9dafa3978f34.png)
![1 3_3](https://user-images.githubusercontent.com/1484773/28154179-612fa2a0-67a9-11e7-9098-96bf856a0c18.png)
![1 3_4](https://user-images.githubusercontent.com/1484773/28154180-6130089e-67a9-11e7-946b-413963fb63d7.png)

**Comment by hofmannc** [comment] 2017-07-13 07:41
Testserver: qa keeper
Browser: ff 
Test date: 12.07.
![grafik](https://user-images.githubusercontent.com/14921701/28155469-33db3c46-67af-11e7-8ac1-e07addb3a71f.png)

![grafik](https://user-images.githubusercontent.com/14921701/28155501-4dc633f4-67af-11e7-8ad7-ef87c5e297f7.png) -> incidation for new notification is orange

**Comment by vmakarenko** [comment] 2017-07-13 16:37
Fixed, except https://user-images.githubusercontent.com/1484773/28154178-612bdbf2-67a9-11e7-8fa8-9dafa3978f34.png, cannolt reproduce

**Comment by hofmannc** [comment] 2017-07-20 07:09
Testserver: qa keeper
Browser: ff
Version: Seafile 6.1.3 ohne Datum 170720
User: logged in

all issues fixed, except "Modification details" could not be reproduced either

**Comment by kleinfe** [comment] 2017-08-01 07:03
checked

**Comment by vmakarenko** [comment] 2017-09-14 14:20
Invitation tip:

**Comment by vmakarenko** [comment] 2018-07-16 14:33
Fixed inivtation tip

**Comment by vmakarenko** [comment] 2018-12-17 13:32
Orange issues in new Markdown Editor (since keeper 1.5)

**Closed** 2020-06-04 08:11 UTC
Labels: bug, gui
