### ISSUE TITLE
Fix bug in share email

### ISSUE THREAD

**Issue by kleinfe** [MPDL/KEEPER#336] opened 2019-03-20 09:02 UTC
When using the link from the share email, i get the information "permission denied".
When using the link in my notifications the link is working

**Comment by vmakarenko** [comment] 2019-03-21 13:27
Cannot reproduce

**Comment by vmakarenko** [comment] 2019-03-27 12:00
Can reproduce: 
Direct email message sent to user has a link to the library of the shared (sub-)directory and not the link of the shared (sub-)directory itself. User message inder the messages bell has a correct link.

**Comment by vmakarenko** [comment] 2019-03-29 12:15
fixed in seafile pro 6.3.13, keeper will be migrated to the version in 1.8

**Comment by vmakarenko** [comment] 2019-07-04 10:58
Fixed by seafile

**Closed** 2020-06-04 08:27 UTC
Labels: bug
